### ISSUE TITLE
Using locale to choose the fromNow string and not the set language

### ISSUE THREAD

**Issue by janepie** [nextcloud-libraries/nextcloud-moment#1061]
When using `moment().fromNow()` the language of the appearing string follows the set locale, not the set language

Visible for example in the trashbin

![Image](https://github.com/user-attachments/assets/51704a2a-5b13-46fd-94f3-813f5f2d503d)

or in the Basic admin settings

![Image](https://github.com/user-attachments/assets/074e872d-2b81-446d-a15c-869a9bb8665c)

## to reproduce
- set your language to English and your locale to German
- check out mentioned pages

**Comment by susnux** [comment]
> Visible for example in the trashbin

Thats not from this library but `NcDatetime` but that should already be fixed.

**Comment by janepie** [comment]
@susnux still happening on master

![Image](https://github.com/user-attachments/assets/1a880054-9790-4dee-bf30-ee120ebaa836)

**Comment by schiessle** [comment]
@susnux can we say already in which Nextcloud version(s) this fix will be released?

**Comment by ShGKme** [comment]
@schiessle It is released in a library. So every app needs to:
- Upgrade `@nextcloud/vue`
- Start using new functions instead of this library

**Comment by susnux** [comment]
For the specific issue it should be fixed with all latest maintenance releases of the server

**Comment by janepie** [comment]
Just checked: Trashbin is fixed, background jobs is not
